route:
  receiver: gmail-notifications

receivers:
  - name: 'gmail-notifications'
    email_configs:
    - to: dima.redkin.1999@gmail.com
      from: dima.redkin.1999@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: dima.redkin.1999@gmail.com
      auth_identity: dima.redkin.1999@gmail.com
      auth_password: kxcqlkcydslnftwm
      send_resolved: true