version: "2.4"

services:
  go-chartographer:
    build: ./go-chartographer
    mem_limit: 2g # по условию задачи
    environment:
      - IMG_DIR=${CONTAINER_IMG_DIR}
    volumes:
      - ${HOST_IMG_DIR}:${CONTAINER_IMG_DIR}
    ports:
      - "8080:8080"

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8081:8080"
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro